### ISSUE TITLE
Additional Output Variables

### ISSUE THREAD

**Issue by merangelik** [nbbrd/rjdemetra#27]
I have two questions concerning the additional output variables that can be defined with the parameter `userdefined` in `x13()`, `x13_def()`, `tramoseats()` and `tramoseats_def()`:

1. Table 9.15 of the _JDemetra+ Reference Manual Version 2.1_ contains the output items _residuals.ser_ and _residuals.ser - ml_ (see p. 283) which are not in included in the vector of names of additional output variables returned by the function `user_defined_variables()` . Instead, `"preprocessing.likelihood.ser"` and `"preprocessing.likelihood.ser-ml"` are returned which on their part are not inclued in Table 9.15. Is that intentional? 
https://github.com/nbbrd/rjdemetra/blob/a8f08fe4cceb49f51e315a5dda3b78ee6edf1003/R/user_defined.R#L78

2. Are `"preprocessing.model.fullresiduals"` and `"preprocessing.residuals.res"` identical? I can not find a documentation for `"preprocessing.residuals.res"` in Table 9.15 of the _JDemetra+ Reference Manual Version 2.1_
https://github.com/nbbrd/rjdemetra/blob/a8f08fe4cceb49f51e315a5dda3b78ee6edf1003/R/user_defined.R#L161
https://github.com/nbbrd/rjdemetra/blob/a8f08fe4cceb49f51e315a5dda3b78ee6edf1003/R/user_defined.R#L177

**Comment by palatej** [comment]
JDemetra+ and RJDemetra use slightly different solutions for generating the results (in fact RJDemetra already uses some technical solutions that will be implemented in JD+ 3.0). That's why there are some small differences/redundancies..., which will be corrected with the release of JD+ 3.0 (not before the end of 2019).
The residuals used in residuals.res are the "full residuals", which correspond to the one-step-ahead forecast errors (obtained by means of the Kalman filter) of y-Xb (y is the series, X the regression variables and b the estimated coefficients). Of course, other definitions would be possible...
